### ISSUE TITLE
tscobj for typo3 12

### ISSUE THREAD

**Issue by drogu02** [simonschaufi/t3ext-tscobj#20]
Do you have any plans to prepare a version of this extension for Typo3 12 soon?

**Comment by simonschaufi** [comment]
Hey, I'm glad that you actually use my extension. Right now you would be the only one who requested an update. Can you sponsor the update? I would highly appreciate any amount!

**Comment by drogu02** [comment]
Done!  I wish other people still use it too! :)

**Comment by simonschaufi** [comment]
Thank you for your support!

**Comment by drogu02** [comment]
Tx for the fast job!
