### ISSUE TITLE
Undefined array key in TypoScriptObjectController.php line 91

### ISSUE THREAD

**Issue by guelzow** [simonschaufi/t3ext-tscobj#26]
Hi everyone.

When using the extension, it throws an undefined array key in the controller in line 91.

**Tested with:**
tscobj 4.0.0
TYPO3 12.4.9
PHP 8.2
lib.someLibrary

**What is happening in the code:**
When using the library "lib.someLibrary", it gets exploded into "lib" and "someLibrary".

[Here](https://github.com/simonschaufi/t3ext-tscobj/blob/master/Classes/Controller/TypoScriptObjectController.php#L90) the code tries to determine the content type.
Normally the TypoScript libraries "lib" does not have a content type.

**Proposed solution:**
Check if the array key exists, with a fallback to NULL.

```php
$contentType = $typoScriptObject[$templatePath[$i]] ?? null;
```

Tobi

**Comment by derBoogie** [comment]
I get this error occasionally in TYPO3 13.4.34 and tscobj 5.0.1

Patch: $typoScriptObject = $typoScriptObject[$templatePath[$i] . '.'] ?? [];

**Comment by simonschaufi** [comment]
@derBoogie I have no idea why you say that you get this error only occasionally. Either your TypoScript is broken or there is some other issue but I'm not aware of any issue as I'm using this extension on a customer project and is very stable there.
Can you please check your TypoScript? Is there any way how I can reproduce this issue?

**Comment by derBoogie** [comment]
@simonschaufi 
Here is my setup.typoscript (uid "3" ist the home page):

```
[traverse(page, "uid") == 3]
lib.programm_empfehlung = USER_INT
lib.programm_empfehlung {
  userFunc = Bs\Sitepackage\Utility\ProgrammEmpfehlungUtility->show
  catIdProgrammHinweis = 1
  eventFolderIDs = 60,62
  urlPath1 = {$baseUrlJTD}programm/event/
  siteName1 = {$siteNameJTD}
  icon1 = blau
  urlPath2 = {$baseUrlKJTD}programm/event/
  siteName2 = {$siteNameKJTD}
  icon2 = rot
  maxItemsToShow = 10
}
[global]
```

"lib.programm_empfehlung" is embedded as a content element on the home page (uid 3). The error does not appear in the log every time the page is loaded, but rather extremely sporadically - that is, a few times a day, completely at random.
